# Generated by Django 4.2.5 on 2023-09-24 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimetoken",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 24, 14, 2, 39, 732935, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
