# Generated by Django 4.2.5 on 2023-09-22 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersApp", "0002_onetimetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimetoken",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 22, 19, 46, 38, 801385, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
