# Generated by Django 4.2.5 on 2023-09-26 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersApp", "0002_alter_onetimetoken_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimetoken",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 26, 0, 59, 20, 845867, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
