# Generated by Django 4.2.5 on 2023-09-23 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersApp", "0005_alter_onetimetoken_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimetoken",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 23, 14, 29, 2, 691601, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
