# Generated by Django 4.2.5 on 2023-09-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="meaning",
            field=models.TextField(default="Not specified"),
        ),
    ]
