# Generated by Django 4.2.5 on 2023-09-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_item_meaning"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
