# Generated by Django 4.2.5 on 2023-09-26 00:48

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_content_system_generated",
            field=markdownx.models.MarkdownxField(
                verbose_name="System Generated Content"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="card_content_user_generated",
            field=markdownx.models.MarkdownxField(
                verbose_name="User Generated Content"
            ),
        ),
    ]
